1000-grub-mount-work-around-bad-integer-comparison.patch: grub-mount: work around bad integer comparison.
gcc says:

  util/grub-mount.c: In function ‘fuse_read’:
  util/grub-mount.c:273:11: error: comparison of integer expressions of different signedness: ‘off_t’ {aka ‘long int’} and ‘grub_off_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
    273 |   if (off > file->size)
        |           ^

This is happening because grub_off_t is unsigned but the system's off_t is
signed.

That's too much work to fix today, so this patch works around it with
tests and typecasting.

Signed-off-by: Peter Jones <pjones@redhat.com>