0123-efi-ip4_config-Improve-check-to-detect-literal-IPv6-.patch: efi/ip4_config: Improve check to detect literal IPv6 addresses
The grub_efi_string_to_ip4_address() function wrongly assumes that an IPv6
address is an IPv4 address, because it doesn't take into account the case
of a caller passing an IPv6 address as a string.

This leads to the grub_efi_net_parse_address() function to fail and print
the following error message:

error: net/efi/net.c:785:unrecognised network address '2000:dead:beef:a::1'

Resolves: rhbz#1732765

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>