Introduce a CI build job
--with-utils=host parameter is required at the configure step
otherwise we see:

    grub_script.yy.h:8:10: fatal error: sys/types.h: No such file or directory
        8 |
          |          ^
    compilation terminated.
    In file included from ./include/grub/misc.h:27,
                     from ./include/grub/dl.h:29,
                     from grub-core/commands/blocklist.c:20:
    ./include/grub/i18n.h:32:12: fatal error: locale.h: No such file or directory
       32 | #  include <locale.h>
          |            ^~~~~~~~~~
    compilation terminated.
    In file included from ./include/grub/misc.h:27,
                     from grub-core/commands/ls.c:21:
    ./include/grub/i18n.h:32:12: fatal error: locale.h: No such file or directory
       32 | #  include <locale.h>
          |            ^~~~~~~~~~

Signed-off-by: Leo Sandoval <lsandova@redhat.com>