fix a bad null check: btrfs: fix a bad null check
current gcc complains:

  grub-core/fs/btrfs.c: In function ‘grub_cmd_btrfs_info’:
  grub-core/fs/btrfs.c:2745:7: error: the comparison will always evaluate as ‘true’ for the address of ‘label’ will never be NULL [-Werror=address]
   2745 |   if (data->sblock.label)
        |       ^~~~
  grub-core/fs/btrfs.c:92:8: note: ‘label’ declared here
     92 |   char label[0x100];
        |        ^~~~~
  cc1: all warnings being treated as errors

Obviously this check should be on the first data byte instead of the
symbol itself.

grub-2.12 rebase:
  Original patch-name: NEW
  Patch modified: no
  Observations: to be fixup/squash with other build issues
  Status: INTERNAL_REVIEW

Signed-off-by: Peter Jones <pjones@redhat.com>